In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from sklearn.metrics import confusion_matrix, precision_score, f1_score, roc_auc_score
from sklearn.linear_model import LogisticRegression

In [2]:
X_train= pd.read_csv("data/X_train.csv", encoding='cp949')
y_train= pd.read_csv("data/y_train.csv", encoding='cp949')
X_test= pd.read_csv("data/X_test.csv", encoding='cp949')

In [3]:
X_train.head()

cust_id      총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0        0  68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1        1   2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2        2   3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3        3  16077620   4935000        NaN      기타   광주점    18  2.444444   
4        4  29050000  24000000        NaN      보석  본  점     2  1.500000   

     주말방문비율  구매주기  
0  0.527027    17  
1  0.000000     1  
2  0.000000     1  
3  0.318182    16  
4  0.000000    85

In [4]:
y_train.gender = y_train.gender.apply(lambda x : '여자' if x ==0 else '남자')
y_train['gender'] = y_train.loc[:,'gender'].apply(lambda x: 1 if x=='남자' else 0)
y_train.head(50)

cust_id  gender
0         0       0
1         1       0
2         2       1
3         3       1
4         4       0
5         5       0
6         6       0
7         7       0
8         8       0
9         9       1
10       10       0
11       11       0
12       12       1
13       13       0
14       14       0
15       15       1
16       16       1
17       17       0
18       18       0
19       19       1
20       20       1
21       21       1
22       22       0
23       23       0
24       24       0
25       25       1
26       26       1
27       27       0
28       28       0
29       29       0
30       30       0
31       31       1
32       32       1
33       33       0
34       34       1
35       35       0
36       36       0
37       37       1
38       38       0
39       39       0
40       40       0
41       41       1
42       42       0
43       43       1
44       44       0
45       45       1
46       46       0
47       47       0
48       48       0
49       49       1

In [5]:
y_train.iloc[:,1] = y_train.gender.map({1:'male', 0:'female'})
y_train

cust_id  gender
0           0  female
1           1  female
2           2    male
3           3    male
4           4  female
...       ...     ...
3495     3495    male
3496     3496    male
3497     3497  female
3498     3498  female
3499     3499  female

[3500 rows x 2 columns]

In [6]:
y_train.gender=y_train.gender.apply(lambda x : 1 if x=='male' else 0)

In [7]:
y_train

cust_id  gender
0           0       0
1           1       0
2           2       1
3           3       1
4           4       0
...       ...     ...
3495     3495       1
3496     3496       1
3497     3497       0
3498     3498       0
3499     3499       0

[3500 rows x 2 columns]

In [8]:
y_train = y_train.iloc[:,1]
y_train

0       0
1       0
2       1
3       1
4       0
       ..
3495    1
3496    1
3497    0
3498    0
3499    0
Name: gender, Length: 3500, dtype: int64

In [9]:
X_train.loc[:,'환불금액'].fillna(0, inplace=True)
X_train.환불금액

0       6860000.0
1        300000.0
2             0.0
3             0.0
4             0.0
          ...    
3495          0.0
3496    6049600.0
3497          0.0
3498          0.0
3499    5973000.0
Name: 환불금액, Length: 3500, dtype: float64

In [10]:
dum_1=pd.get_dummies(X_train['주구매상품'])

In [11]:
dum_2=pd.get_dummies(X_train['주구매지점'])

In [12]:
X_train=pd.concat([X_train, dum_1, dum_2], axis=1)

In [13]:
X_train.drop(['cust_id','주구매상품','주구매지점'], axis=1, inplace=True)

In [14]:
X_train

총구매액     최대구매액       환불금액  내점일수   내점당구매건수    주말방문비율  구매주기  가공식품  \
0      68282840  11264000  6860000.0    19  3.894737  0.527027    17     0   
1       2136000   2136000   300000.0     2  1.500000  0.000000     1     0   
2       3197000   1639000        0.0     2  2.000000  0.000000     1     0   
3      16077620   4935000        0.0    18  2.444444  0.318182    16     0   
4      29050000  24000000        0.0     2  1.500000  0.000000    85     0   
...         ...       ...        ...   ...       ...       ...   ...   ...   
3495    3175200   3042900        0.0     1  2.000000  1.000000     0     0   
3496   29628600   7200000  6049600.0     8  1.625000  0.461538    40     0   
3497      75000     75000        0.0     1  1.000000  0.000000     0     0   
3498    1875000   1000000        0.0     2  1.000000  0.000000    39     0   
3499  263101550  34632000  5973000.0    38  2.421053  0.467391     8     0   

      가구  건강식품  ...  안양점  영등포점  울산점  인천점  일산점  잠실점  전주점  창원점  청량리점  포항점  
0      0     0  ...    0     0    0    0    0    0    0    0     0    0  
1      0     0  ...    0     0    0    0    0    1    0    0     0    0  
2      0     0  ...    0     0    0    0    0    0    0    0     0    0  
3      0     0  ...    0     0    0    0    0    0    0    0     0    0  
4      0     0  ...    0     0    0    0    0    0    0    0     0    0  
...   ..   ...  ...  ...   ...  ...  ...  ...  ...  ...  ...   ...  ...  
3495   0     0  ...    0     0    0    0    0    0    0    0     0    0  
3496   0     0  ...    0     0    0    0    0    0    0    0     0    0  
3497   0     0  ...    0     0    0    0    0    0    0    1     0    0  
3498   0     0  ...    0     0    0    0    0    0    0    0     0    0  
3499   0     0  ...    0     0    0    0    0    0    0    0     0    0  

[3500 rows x 73 columns]

In [15]:
scale= MinMaxScaler()
X_train=scale.fit_transform(X_train)
X_train

array([[5.08100182e-02, 2.00895971e-02, 1.21684497e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.29657701e-02, 7.22639268e-03, 5.32147944e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.34123938e-02, 6.52601882e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.20982004e-02, 4.32202542e-03, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.28559032e-02, 5.62553814e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.32818176e-01, 5.30198514e-02, 1.05950656e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [16]:
y_train

0       0
1       0
2       1
3       1
4       0
       ..
3495    1
3496    1
3497    0
3498    0
3499    0
Name: gender, Length: 3500, dtype: int64

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2)

In [18]:
X_test, y_test

(array([[0.02902229, 0.00689382, 0.00212859, ..., 0.        , 0.        ,
         0.        ],
        [0.07659529, 0.02278399, 0.00184389, ..., 0.        , 0.        ,
         0.        ],
        [0.0993683 , 0.05562406, 0.05578808, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.02543209, 0.01305908, 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.02665485, 0.01023363, 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.02580842, 0.01547869, 0.        , ..., 0.        , 1.        ,
         0.        ]]),
 3157    0
 1238    1
 889     0
 1632    0
 2912    0
        ..
 3073    0
 210     0
 3046    1
 3392    0
 1932    1
 Name: gender, Length: 700, dtype: int64)

In [28]:
X_train.shape

(2800, 73)

In [30]:
np.unique(X_train)
X_train.shape

(2800, 73)

In [19]:
k_f = KFold(n_splits=5, shuffle=True, random_state=123)

In [20]:
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_train,y_train)

0.6675

In [21]:
model.score(X_test,y_test)

0.6242857142857143

In [22]:
cross_val_score(model,X_test, y_test, cv=k_f)

array([0.58571429, 0.57142857, 0.60714286, 0.57142857, 0.62857143])

In [23]:
print(model.coef_)

[[-1.21598779 -1.03341971 -1.61488606 -1.88776212 -0.51859226  0.45597861
   0.01469838  0.01697719 -0.09012601  0.2521889   0.41287108  0.20872911
  -0.11628884  1.21123743  0.54171412  1.09796821 -0.38374793 -0.71417708
  -1.32761788 -0.1233385  -0.08313203 -0.52661541 -0.21115246  0.38906574
   0.20966705  0.80067682  0.00770096 -0.29355476  0.39124875 -1.13843248
   0.57445076 -0.31854462  0.65033005 -0.65093685 -0.02744608 -0.41643209
  -0.08886555  1.10556238  0.84290365  0.14165202 -0.3297065   0.0090968
  -0.98934154 -0.32644002 -0.51123517  0.68694535 -0.04282529 -0.06779967
  -0.77022935 -0.69199037  0.1042282   0.22294362 -0.43317959  0.53726121
  -0.00744532 -0.33569593  0.1013789   0.02982532 -0.34318519 -0.33514826
  -0.28796501 -0.1234422   0.15431612  0.28931816 -0.03097603  0.65949631
   0.45731236  0.00615594 -0.30090939  1.00681397 -0.28084827 -0.15818016
  -0.23708408]]


In [24]:
print(model.intercept_)

[-0.08364088]


In [25]:
predict=model.predict(X_test)

In [26]:
roc_auc_score(predict, y_test)

0.612237874546873