In [1]:
import pandas as pd

In [84]:
X_train = pd.read_csv("data/X_train.csv", encoding='cp949')
y_train = pd.read_csv("data/y_train.csv", encoding='cp949')
X_test = pd.read_csv("data/X_test.csv", encoding='cp949')

In [85]:
X_train["gender"] = y_train['gender']

In [86]:
X_train.head(5)

cust_id      총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0        0  68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1        1   2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2        2   3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3        3  16077620   4935000        NaN      기타   광주점    18  2.444444   
4        4  29050000  24000000        NaN      보석  본  점     2  1.500000   

     주말방문비율  구매주기  gender  
0  0.527027    17       0  
1  0.000000     1       0  
2  0.000000     1       1  
3  0.318182    16       1  
4  0.000000    85       0

In [87]:
X_train['환불금액'].fillna(0, inplace=True)

# EDA

In [38]:
X_train.groupby(['주구매상품','gender']).count().unstack()

cust_id          총구매액         최대구매액          환불금액         주구매지점         \
gender       0      1      0      1      0      1      0      1      0      1   
주구매상품                                                                           
가공식품     317.0  229.0  317.0  229.0  317.0  229.0  317.0  229.0  317.0  229.0   
가구         5.0    5.0    5.0    5.0    5.0    5.0    5.0    5.0    5.0    5.0   
건강식품      22.0   25.0   22.0   25.0   22.0   25.0   22.0   25.0   22.0   25.0   
골프        38.0   44.0   38.0   44.0   38.0   44.0   38.0   44.0   38.0   44.0   
구두        26.0   28.0   26.0   28.0   26.0   28.0   26.0   28.0   26.0   28.0   
기타       375.0  220.0  375.0  220.0  375.0  220.0  375.0  220.0  375.0  220.0   
남성 캐주얼    13.0   42.0   13.0   42.0   13.0   42.0   13.0   42.0   13.0   42.0   
남성 트랜디     1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0   
남성정장       4.0   18.0    4.0   18.0    4.0   18.0    4.0   18.0    4.0   18.0   
농산물      247.0   92.0  247.0   92.0  247.0   92.0  247.0   92.0  247.0   92.0   
대형가전       4.0    4.0    4.0    4.0    4.0    4.0    4.0    4.0    4.0    4.0   
디자이너     168.0   25.0  168.0   25.0  168.0   25.0  168.0   25.0  168.0   25.0   
란제리/내의     6.0    2.0    6.0    2.0    6.0    2.0    6.0    2.0    6.0    2.0   
명품        61.0   39.0   61.0   39.0   61.0   39.0   61.0   39.0   61.0   39.0   
모피/피혁     39.0   18.0   39.0   18.0   39.0   18.0   39.0   18.0   39.0   18.0   
보석         2.0    1.0    2.0    1.0    2.0    1.0    2.0    1.0    2.0    1.0   
생활잡화       8.0    7.0    8.0    7.0    8.0    7.0    8.0    7.0    8.0    7.0   
섬유잡화      48.0   50.0   48.0   50.0   48.0   50.0   48.0   50.0   48.0   50.0   
셔츠        11.0   19.0   11.0   19.0   11.0   19.0   11.0   19.0   11.0   19.0   
소형가전       1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0   
수산품       92.0   61.0   92.0   61.0   92.0   61.0   92.0   61.0   92.0   61.0   
스포츠       33.0   36.0   33.0   36.0   33.0   36.0   33.0   36.0   33.0   36.0   
시티웨어     169.0   44.0  169.0   44.0  169.0   44.0  169.0   44.0  169.0   44.0   
식기         2.0    5.0    2.0    5.0    2.0    5.0    2.0    5.0    2.0    5.0   
아동        26.0   14.0   26.0   14.0   26.0   14.0   26.0   14.0   26.0   14.0   
악기         NaN    2.0    NaN    2.0    NaN    2.0    NaN    2.0    NaN    2.0   
액세서리       4.0    1.0    4.0    1.0    4.0    1.0    4.0    1.0    4.0    1.0   
육류        31.0   26.0   31.0   26.0   31.0   26.0   31.0   26.0   31.0   26.0   
일용잡화      43.0   21.0   43.0   21.0   43.0   21.0   43.0   21.0   43.0   21.0   
젓갈/반찬     14.0   15.0   14.0   15.0   14.0   15.0   14.0   15.0   14.0   15.0   
주류         3.0   11.0    3.0   11.0    3.0   11.0    3.0   11.0    3.0   11.0   
주방가전       8.0   18.0    8.0   18.0    8.0   18.0    8.0   18.0    8.0   18.0   
주방용품      18.0   14.0   18.0   14.0   18.0   14.0   18.0   14.0   18.0   14.0   
차/커피      26.0   18.0   26.0   18.0   26.0   18.0   26.0   18.0   26.0   18.0   
축산가공      19.0   16.0   19.0   16.0   19.0   16.0   19.0   16.0   19.0   16.0   
침구/수예      4.0    NaN    4.0    NaN    4.0    NaN    4.0    NaN    4.0    NaN   
캐주얼       60.0   41.0   60.0   41.0   60.0   41.0   60.0   41.0   60.0   41.0   
커리어        6.0    3.0    6.0    3.0    6.0    3.0    6.0    3.0    6.0    3.0   
통신/컴퓨터     1.0    2.0    1.0    2.0    1.0    2.0    1.0    2.0    1.0    2.0   
트래디셔널     12.0   11.0   12.0   11.0   12.0   11.0   12.0   11.0   12.0   11.0   
피혁잡화      21.0   19.0   21.0   19.0   21.0   19.0   21.0   19.0   21.0   19.0   
화장품      196.0   68.0  196.0   68.0  196.0   68.0  196.0   68.0  196.0   68.0   

         내점일수        내점당구매건수        주말방문비율          구매주기         
gender      0      1       0      1      0      1      0      1  
주구매상품                                                            
가공식품    317.0  229.0   317.0  229.0  317.0  229.0  317.0  229.0  
가구        5.0    5.0     5.0    5.0    5.0    5.0    5.0    5.0  
건강식품     22.0   25.0    22.0   

In [42]:
X_train.groupby(['주구매상품','gender'])['주구매지점'].count().unstack()

gender      0      1
주구매상품               
가공식품    317.0  229.0
가구        5.0    5.0
건강식품     22.0   25.0
골프       38.0   44.0
구두       26.0   28.0
기타      375.0  220.0
남성 캐주얼   13.0   42.0
남성 트랜디    1.0    1.0
남성정장      4.0   18.0
농산물     247.0   92.0
대형가전      4.0    4.0
디자이너    168.0   25.0
란제리/내의    6.0    2.0
명품       61.0   39.0
모피/피혁    39.0   18.0
보석        2.0    1.0
생활잡화      8.0    7.0
섬유잡화     48.0   50.0
셔츠       11.0   19.0
소형가전      1.0    1.0
수산품      92.0   61.0
스포츠      33.0   36.0
시티웨어    169.0   44.0
식기        2.0    5.0
아동       26.0   14.0
악기        NaN    2.0
액세서리      4.0    1.0
육류       31.0   26.0
일용잡화     43.0   21.0
젓갈/반찬    14.0   15.0
주류        3.0   11.0
주방가전      8.0   18.0
주방용품     18.0   14.0
차/커피     26.0   18.0
축산가공     19.0   16.0
침구/수예     4.0    NaN
캐주얼      60.0   41.0
커리어       6.0    3.0
통신/컴퓨터    1.0    2.0
트래디셔널    12.0   11.0
피혁잡화     21.0   19.0
화장품     196.0   68.0

In [14]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cust_id  3500 non-null   int64  
 1   총구매액     3500 non-null   int64  
 2   최대구매액    3500 non-null   int64  
 3   환불금액     3500 non-null   float64
 4   주구매상품    3500 non-null   object 
 5   주구매지점    3500 non-null   object 
 6   내점일수     3500 non-null   int64  
 7   내점당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64  
 10  gender   3500 non-null   int64  
dtypes: float64(3), int64(6), object(2)
memory usage: 300.9+ KB


# 정제

In [49]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, OneHotEncoder

In [43]:
X_train.head(5)

cust_id      총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0        0  68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1        1   2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2        2   3197000   1639000        0.0  남성 캐주얼   관악점     2  2.000000   
3        3  16077620   4935000        0.0      기타   광주점    18  2.444444   
4        4  29050000  24000000        0.0      보석  본  점     2  1.500000   

     주말방문비율  구매주기  gender  
0  0.527027    17       0  
1  0.000000     1       0  
2  0.000000     1       1  
3  0.318182    16       1  
4  0.000000    85       0

In [91]:
X_train['총구매액'] = MinMaxScaler().fit_transform(X_train[['총구매액']])
X_train['최대구매액'] = MinMaxScaler().fit_transform(X_train[['최대구매액']])
X_train['환불금액'] = MinMaxScaler().fit_transform(X_train[['환불금액']])
X_train['내점일수'] = MinMaxScaler().fit_transform(X_train[['내점일수']])
X_train['내점당구매건수'] = MinMaxScaler().fit_transform(X_train[['내점당구매건수']])
X_train['구매주기'] = MinMaxScaler().fit_transform(X_train[['구매주기']])

In [123]:
ltmp = LabelEncoder().fit_transform(X_train['주구매상품'])
ltmp

array([ 5, 21,  6, ..., 32, 41,  5])

In [126]:
ltmp = ltmp.reshape(-1,1)
etmp = OneHotEncoder().fit_transform(ltmp)
etmp = etmp.toarray()
print(etmp)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [92]:
X_train.head(5)

cust_id      총구매액     최대구매액      환불금액   주구매상품 주구매지점      내점일수   내점당구매건수  \
0        0  0.050810  0.020090  0.012168      기타   강남점  0.063380  0.137300   
1        1  0.022966  0.007226  0.000532     스포츠   잠실점  0.003521  0.023715   
2        2  0.023412  0.006526  0.000000  남성 캐주얼   관악점  0.003521  0.047431   
3        3  0.028834  0.011171  0.000000      기타   광주점  0.059859  0.068511   
4        4  0.034295  0.038037  0.000000      보석  본  점  0.003521  0.023715   

     주말방문비율      구매주기  gender  
0  0.527027  0.102410       0  
1  0.000000  0.006024       0  
2  0.000000  0.006024       1  
3  0.318182  0.096386       1  
4  0.000000  0.512048       0

In [103]:
import sklearn.preprocessing 
help(OneHotEncoder)

Help on class OneHotEncoder in module sklearn.preprocessing._encoders:

class OneHotEncoder(_BaseEncoder)
 |  Encode categorical features as a one-hot numeric array.
 |  
 |  The input to this transformer should be an array-like of integers or
 |  strings, denoting the values taken on by categorical (discrete) features.
 |  The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
 |  encoding scheme. This creates a binary column for each category and
 |  returns a sparse matrix or dense array (depending on the ``sparse``
 |  parameter)
 |  
 |  By default, the encoder derives the categories based on the unique values
 |  in each feature. Alternatively, you can also specify the `categories`
 |  manually.
 |  
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard kernels.
 |  
 |  Note: a one-hot encoding of y labels should use a LabelBinarizer
 |  instead.
 |  
 |  Read more in the :ref: